### ISSUE TITLE
is it possible to add support of safetensors checkpoints?

### ISSUE THREAD

**Issue by fractal-fumbler** [deGENERATIVE-SQUAD/stable-diffusion-losslessmix-v2#1]
was researching model mixing with https://reddit.com/r/StableDiffusion/comments/11670e7/maximal_merge_merging_multiple_models_with_source/ and stumbled upon your repo.

most checkpoints atm are in safetensors formart.
can you please add support for mixing this format too?

**Comment by deGENERATIVE-SQUAD** [comment]
> can you please add support for mixing this format too?
Thanks for feedback, I think yes. Trying to add in next versions.

>most checkpoints atm are in safetensors formart.
If you want you can convert any model in CKPT format through https://github.com/diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI or https://github.com/bbc-mc/sdweb-merge-block-weighted-gui. But before converting I recommend to prune the model through https://github.com/arenatemp/stable-diffusion-webui-model-toolkit
