### ISSUE TITLE
missing -- in losslessmixv2.1cs.py

### ISSUE THREAD

**Issue by fractal-fumbler** [deGENERATIVE-SQUAD/stable-diffusion-losslessmix-v2#2]
hello :)
thanks a lot for your work, been playing around with scripts for a while :)

sorry for bothering. 
noticed that in `losslessmixv2.1cs` double - is missing in model argument 
https://github.com/deGENERATIVE-SQUAD/stable-diffusion-losslessmix-v2/blob/eec6f6adbd44bddf9b206aa5aac6c315f4a86207/losslessmixv2.1cs.py#L8

**Comment by deGENERATIVE-SQUAD** [comment]
Hi! 
Arg with '--' is not needed in this case, use it just like
**python script.py model.ckpt model.ckpt model.ckpt --out name**

**Comment by fractal-fumbler** [comment]
gotcha.
thanks a lot :)
